#Copyright Berezhnoy LN

version: '3.7'
services:
  rosgrant-elasticsearch:
    image: elasticsearch:5.6.8-alpine
    container_name: rosgrant-elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
    environment:
        - discovery.type=single-node
    restart: always
  rosgrant-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: rosgrant-sql
    ports:
        - 1433:1433
    volumes:
        - mssql-data:/var/opt/mssql
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: myStrongPass2020
    restart: always
  rosgrant-redis:
    image: redis:3.2.10
    container_name: rosgrant-redis
    ports:
        - 6379:6379
    volumes:
        - redis-data:/data
    restart: always
  rosgrant-rabbit:
    image: rabbitmq:management
    container_name: rosgrant-rabbitmq
    ports:
        - 15672:15672
        - 5672:5672
        - 25672:25672
    volumes:
        - rabbitmq-schema:/var/lib/rabbitmq/schema 
        - rabbitmq-mnesia:/var/lib/rabbitmq/mnesia 
        - rabbitmq-config:/var/lib/rabbitmq/config 
    restart: always
  rosgrant-identity:
    image: levnikolaevich/rosgrantidentity:latest
    container_name: rosgrant-identity
    volumes:
        - uploaded-files:/var/uploaded_files
    environment:
        ASPNETCORE_ENVIRONMENT: DockerTest
    depends_on:
        - rosgrant-mssql
        - rosgrant-redis
        - rosgrant-rabbit    
    restart: always
  rosgrant-mvc:
    image: levnikolaevich/rosgrantmvc:latest
    container_name: rosgrant-mvc
    volumes:
       - uploaded-files:/var/uploaded_files
    environment:
        ASPNETCORE_ENVIRONMENT: DockerTest
    depends_on:
        - rosgrant-mssql
        - rosgrant-redis
        - rosgrant-rabbit
        - rosgrant-identity    
    restart: always
  rosgrant-user:
        image: levnikolaevich/rosgrantuser:latest
        container_name: rosgrant-user
        volumes:
            - uploaded-files:/var/uploaded_files
        environment:
            ASPNETCORE_ENVIRONMENT: DockerTest
        depends_on:
            - rosgrant-mssql
            - rosgrant-redis
            - rosgrant-rabbit
            - rosgrant-identity    
        restart: always
  rosgrant-emailtemplate:
        image: levnikolaevich/rosgrantemailtemplate:latest
        container_name: rosgrant-emailtemplate
        volumes:
            - uploaded-files:/var/uploaded_files
        environment:
            ASPNETCORE_ENVIRONMENT: DockerTest
        depends_on:
            - rosgrant-mssql
            - rosgrant-redis
            - rosgrant-rabbit
            - rosgrant-identity    
        restart: always 
  rosgrant-application:
        image: levnikolaevich/rosgrantapplication:latest
        container_name: rosgrant-application
        volumes:
            - uploaded-files:/var/uploaded_files
        environment:
            ASPNETCORE_ENVIRONMENT: DockerTest
        depends_on:
            - rosgrant-mssql
            - rosgrant-redis
            - rosgrant-rabbit
            - rosgrant-identity    
        restart: always        
  rosgrant-proxy:
    image: levnikolaevich/rosgrantproxy:latest
    container_name: rosgrant-proxy
    ports:
        - 80:80
    environment:
        ASPNETCORE_ENVIRONMENT: DockerTest
    depends_on:
        - rosgrant-identity
    restart: always      

volumes:
    rabbitmq-schema: 
    rabbitmq-mnesia:
    rabbitmq-config:
    mssql-data:
    redis-data:
    uploaded-files:        